# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2869202442b38a5d614b55a4e45c69dac57aae082ea854eaf4438ed379c43138a1d38522e6d078fa35a72ba192aa715d0b2c9b65c001de735572dfd997281269

test:
  secret_key_base: e785d3aaec1a4c1093c7178b02cd9990e5207cb734425faa0945eb4794b720dfeac1a8c0557c015f6b7f0bbfe2e4e1f23a2ec9a6fcf90e81665bb86eb571706a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
